# Generated by Django 2.2 on 2020-06-06 16:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200606_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
